# # .gitlab-ci.yml
# stages:
#   - build
#   - test
#   - coverage


# image: maven:3.8.6-eclipse-temurin-17
# build:
#   stage: build
#   script: 
#     - mvn clean compile
#   artifacts:
#     paths: 
#       - target/

# # Test Job
# test:
#   stage: test
#   script:
#     - echo "Connecting to GCP MySQL instance..."
#     - mvn test -X
#   artifacts:
#     paths:
#       - target/  # Save compiled files and test results for the next stage

# # Coverage Job
# coverage:
#   stage: coverage
#   script:
#     - echo "Generating code coverage report with JaCoCo..."
#     - mvn jacoco:report  # Generate JaCoCo coverage report
#   dependencies:
#     - test  # Use the artifacts from the test job
#   artifacts:
#     paths:
#       - target/site/jacoco/  # Save the JaCoCo report as an artifact
#     expire_in: 1 week  # Optional: Set expiration time for the artifacts
#############################################################################################
stages:
  - build
  - test
 
# Use Maven with OpenJDK 17 from Eclipse Temurin
image: maven:3.8.6-eclipse-temurin-17

variables:
  DB_URL: $DB_URL
  DB_USER: $DB_USER
  DB_PASSWORD: $DB_PASSWORD
  GCP_PROJECT_ID: maximal-brace-436007-t5
  # WORKLOAD_IDENTITY_POOL: airline-javaapp-pool
  # GCP_WORKLOAD_IDENTITY_PROVIDER: "projects/maximal-brace-436007-t5/locations/global/workloadIdentityPools/airline-javaapp-pool"
  # SERVICE_ACCOUNT_EMAIL: java-app-sa@maximal-brace-436007-t5.iam.gserviceaccount.com


# before_script:  
#   # Install Google Cloud SDK
#   - apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg
#   - echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
#   - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
#   - apt-get update && apt-get install -y google-cloud-sdk
  
#   - echo "$SERVICE_ACCOUNT_EMAIL"
  # - gcloud projects add-iam-policy-binding $GCP_PROJECT_ID \
  #   --member="serviceAccount:$SERVICE_ACCOUNT_EMAIL" \
  #   --role="roles/iam.workloadIdentityPoolAdmin"
  # - echo "Checking with GCP using Workload Identity Federation"
  # - gcloud iam workload-identity-pools describe airline-javaapp-pool --location global --project=maximal-brace-436007-t5
  # # # Set project and service account using the integrated Workload Identity Federation
  # - gcloud config set project $GCP_PROJECT_ID
  # - gcloud config set account $SERVICE_ACCOUNT_EMAIL

  #   # Authenticate using Workload Identity Federation (WIF)
  # - gcloud auth login --enable-gdrive-access --impersonate-service-account=$SERVICE_ACCOUNT_EMAIL --allow-local-impersonation --workload-identity-federation

# Build Job 
build:
  stage: build
  script: 
    - mvn clean compile
  artifacts:
    paths:
      - target/

# Test Job
test:
  stage: test
  script:
    - echo "Connecting to GCP MySQL instance..."
    - mvn test -X

#######################################################
# stages:
#   - build 
#   - test

# # Use Maven with OpenJDK 17 from Eclipse Temurin
# image: maven:3.8.6-eclipse-temurin-17

# variables:
#   DB_URL: $DB_URL
#   DB_USER: $DB_USER
#   DB_PASSWORD: $DB_PASSWORD

# image: google/cloud-sdk:latest

# variables:
#   GCP_PROJECT_ID: your-project-id
#   GCP_WORKLOAD_IDENTITY_PROVIDER: https://your-workload-identity-provider-url
#   SERVICE_ACCOUNT_EMAIL: your-service-account@your-project.iam.gserviceaccount.com

# before_script:
#   - gcloud auth activate-service-account --key-file=/etc/gitlab-runner/config.toml
#   - gcloud config set project $GCP_PROJECT_ID
#   - gcloud config set account $SERVICE_ACCOUNT_EMAIL
#   - gcloud config set workload-identity-provider $GCP_WORKLOAD_IDENTITY_PROVIDER


# # Build Job
# build:
#   stage: build
#   script: 
#     - mvn clean compile
#   artifacts:
#     paths: 
#       - target/  

# # Test Job
# test:
#   stage: test
#   script:
#     - echo "Connecting to GCP MySQL instance..."
#     - mvn test -X  