# .gitlab-ci.yml

stages:
  - build 
  - test

# Use Maven with OpenJDK 17 from Eclipse Temurin
image: maven:3.8.6-eclipse-temurin-17

variables:
  DB_URL: $DB_URL
  DB_USER: $DB_USER
  DB_PASSWORD: $DB_PASSWORD



# Build Job
build:
  stage: build
  script: 
    - mvn clean compile
  artifacts:
    paths: 
      - target/  

# Test Job
test:
  stage: test
  script:
    - echo "Connecting to GCP MySQL instance..."
    - mvn test -X  