apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for all resources
namespace: airline-app

# Resources to deploy in order
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - app-deployment.yaml
  - app-service.yaml

# Common labels applied to all resources
commonLabels:
  project: airline-management-system
  managed-by: kustomize

# Images to be replaced (useful for CI/CD)
images:
  - name: us-central1-docker.pkg.dev/dauntless-ether-447206-i7/airline-app-repository/airline-app-image
    newTag: latest
