# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation. 

name: Java CI with Maven 
 
on:
  push: 
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ] 

permissions:  
  contents: read     
  id-token: write
   
jobs: 
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set Environment Variables
      run: |
        echo "SPRING_DATASOURCE_USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
        echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
        
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: table
        severity: 'CRITICAL'


    - name: Build and run tests with Maven
      run: mvn -B clean test --file pom.xml


    - name: Generate JaCoCo code coverage report
      run: mvn jacoco:report --file pom.xml
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2.0.0  
      with:
          workload_identity_provider: projects/646247534868/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc
          service_account: java-app-github-actions@dauntless-ether-447206-i7.iam.gserviceaccount.com

    - name: Chcking
      run: gsutil ls 
    - name: Configure Docker for GCR
      run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
 
    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
          docker build -t us-central1-docker.pkg.dev/dauntless-ether-447206-i7/airline-app-repository/airline-app-image:${{ github.sha }} .
         

    - name: Push Docker image
      run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker push us-central1-docker.pkg.dev/dauntless-ether-447206-i7/airline-app-repository/airline-app-image:${{ github.sha }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.0.0

      # Step 4: Install gsutil (gsutil is part of gcloud, so this might not be needed if already installed)
    - name: Install gsutil
      run: |
          gcloud components install gsutil
          gsutil ls


    - name: Checking it 
      run: gsutil ls
